---
- name: Add an Apt signing key for kubectl
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
  tags: helm

- name: Add specified repository into sources list using specified filename
  ansible.builtin.apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
    filename: helm-stable-debian
  tags: helm

- name: install helm
  package:
    name:
      - helm
    state: present
    update_cache: true
  tags: helm