---
- name: Add the HashiCorp GPG key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
    become: yes
  tags: helm

- name: Add specified repository into sources list using specified filename
  ansible.builtin.apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
    filename: helm
  tags: helm

- name: install helm
  package:
    name:
      - helm
    state: present
    update_cache: true
  tags: helm