---
- name: Install tmux
  apt:
    name: 
    - tmux
    state: present
    update_cache: yes
  become: yes
  
- name: Check if tmux-plugins/tpm exists
  stat:
    path: "{{ ansible_env_home }}/.tmux/plugins/tpm"
  register: tmux_plugins_tpm
  tags: tmux

- name: Cloning  https://github.com/tmux-plugins/tpm
  ansible.builtin.git :
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env_home }}/.tmux/plugins/tpm"
    update: no
  when: not tmux_plugins_tpm.stat.exists
  tags: tmux

- name: Check .tmux.conf for users
  stat:
    path: "{{ ansible_env_home }}/.tmux.conf"
  register: stat_tmux_conf
  tags: tmux

- name: write .tmux.conf for users
  template:
    src: .tmux.conf.j2
    dest: '{{ ansible_env_home }}/.tmux.conf'
    backup: yes
    mode: '744'
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
  when: not stat_tmux_conf.stat.exists
  tags: tmux

- name: Check .tmux folder for users
  stat:
    path: "{{ ansible_env_home }}/.tmux"
  register: stat_tmux_folder
  tags: tmux

- name: recursively update .tmux folder
  ansible.builtin.file:
    path: "{{ ansible_env_home }}/.tmux"
    state: directory
    recurse: yes
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
  when: not stat_tmux_folder.stat.exists
  tags: tmux

