name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Cache Vagrant boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-

    - name: Install virtualbox & vagrant
      run: |      
        sudo apt-get update -y && sudo apt-get install -y virtualbox vagrant
        pip3 -q install ansible==2.10.7

    - name: Show Vagrant version
      run: vagrant --version

    - name: Run vagrant up
      run: vagrant up

    - name: ssh into box after boot
      run: vagrant ssh -c "echo 'hello world!'"